name: Lint Commit Messages

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ${{ vars.RUNNER || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.cjs
