name: Lint Commit Messages

on: [pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ${{ vars.RUNNER != '' && vars.RUNNER || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
