name: Renovate

on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: "1 11 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  RENOVATE_DRY_RUN: "full"

jobs:
  run-ci:
    runs-on: ${{ vars.RUNNER != '' && vars.RUNNER || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40
        with:
          configurationFile: .github/renovate-config.cjs
          token: ${{ secrets.RENOVATE_TOKEN }}
